// Generated by CoffeeScript 1.4.0
(function() {
  var GelbooruCrawler, conf, fs, http, path, test, util, _,
    __slice = [].slice;

  _ = require("underscore");

  util = require("util");

  path = require("path");

  fs = require("fs");

  http = require("http");

  require("colors");

  GelbooruCrawler = (function() {

    function GelbooruCrawler(query, config) {
      this.baseUrl = config.baseUrl;
      this.maxWorkers = config.maxWorkers || 5;
      this.maxDownloads = config.maxDownloads || 4;
      this.renameFiles = config.renameFiles || true;
      this.query = query || "";
    }

    GelbooruCrawler.prototype.baseUrl = null;

    GelbooruCrawler.prototype.browseUrl = "/index.php?page=post&s=list";

    GelbooruCrawler.prototype.viewUrl = "/index.php?page=post&s=view&id=";

    GelbooruCrawler.prototype.searchUrlBase = null;

    GelbooruCrawler.prototype.crawledImages = [];

    GelbooruCrawler.prototype.resolveQueue = [];

    GelbooruCrawler.prototype.workers = [];

    GelbooruCrawler.prototype.query = null;

    GelbooruCrawler.prototype.galleryName = null;

    GelbooruCrawler.prototype.pageId = null;

    GelbooruCrawler.prototype.running = false;

    GelbooruCrawler.prototype.crawling = false;

    GelbooruCrawler.prototype.downloadPath = null;

    GelbooruCrawler.prototype.totalFiles = 0;

    GelbooruCrawler.prototype.crawls = 0;

    GelbooruCrawler.prototype.workerColors = ['yellow', 'red', 'green', 'blue', 'white', 'cyan', 'magenta'];

    GelbooruCrawler.prototype.imageIdRegExp = /index\.php\?page=post&amp;s=view&amp;id=(\d+)/ig;

    GelbooruCrawler.prototype.imageUrlRegExp = /http:\/\/cdn\d+.*(\/?images\/\d+\/[a-f0-9]+\.(jpe?g|png|gif))/ig;

    GelbooruCrawler.prototype.log = function() {
      var bold, col, colId, message, mymsg, out, w, worker, _i, _len;
      worker = arguments[0], message = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (worker != null) {
        w = this.workers.indexOf(worker);
      }
      if ((w != null) && w !== -1) {
        col = w % (this.workerColors.length * 2);
        colId = col % this.workerColors.length;
        if (col > this.workerColors.length) {
          bold = true;
        }
        out = [];
        for (_i = 0, _len = message.length; _i < _len; _i++) {
          mymsg = message[_i];
          if (bold != null) {
            mymsg = mymsg.bold;
          }
          out.push(mymsg[this.workerColors[colId]]);
        }
        return util.log.apply(null, out);
      } else {
        return util.log.apply(null, message);
      }
    };

    GelbooruCrawler.prototype.search = function() {
      var negative, positive, tag, tags, _fn, _i, _len,
        _this = this;
      tags = this.query.split(/\s+/);
      positive = [];
      negative = [];
      _fn = function(tag) {
        return (tag.charAt(0) === "-" ? negative : positive).push(tag.replace(/\-/g, "not-").replace(/_/g, "-").replace(/[^a-z\-]/gi, ""));
      };
      for (_i = 0, _len = tags.length; _i < _len; _i++) {
        tag = tags[_i];
        _fn(tag);
      }
      this.galleryName = positive.join(", ") + " (" + negative.join(", ") + ")";
      this.createPath();
      this.searchUrlBase = "" + this.browseUrl + "&tags=" + (escape(this.query)) + "&pid=";
      this.pageId = 0;
      this.running = true;
      this.crawling = true;
      this.log(null, "BaseURL: " + this.baseUrl);
      this.log(null, "Search: " + this.query);
      this.log(null, " -> include: " + (positive.join(", ")));
      this.log(null, " -> exclude: " + (negative.join(", ")));
      this.log(null, "Gallery Name: " + this.galleryName);
      this.log(null, "Starting crawler ... max. " + this.maxWorkers + " requests");
      return process.nextTick(function() {
        return _this.crawl();
      });
    };

    GelbooruCrawler.prototype.crawl = function() {
      var imageId,
        _this = this;
      while (this.workers.length < this.maxWorkers) {
        this.crawls++;
        if (this.crawling && !this.resolveQueue.length) {
          this.spawnWorker(this.searchUrlBase + this.pageId, this.scanPage);
          this.pageId += 28;
        } else if (this.resolveQueue.length) {
          imageId = this.resolveQueue.pop();
          this.resolveImageId(imageId);
        }
        this.log(null, ("Pass: " + this.crawls + " Threads: " + this.workers.length + "/" + this.maxWorkers).underline);
        this.log(null, ("Found: " + this.crawledImages.length + " images").underline);
      }
      return process.nextTick(function() {
        var crawl;
        crawl = function() {
          return _this.crawl();
        };
        if (_this.crawling || _this.resolveQueue.length) {
          return setTimeout(crawl, 2000);
        }
      });
    };

    GelbooruCrawler.prototype.downloadImage = function(url) {
      var filename;
      return filename = this.downloadPath + "/" + path.basename(url, true);
    };

    GelbooruCrawler.prototype.spawnWorker = function(url, callback) {
      var requestUrl, worker,
        _this = this;
      requestUrl = url;
      this.log(this.workers.length, "Spawning worker for: " + requestUrl);
      worker = http.get(this.baseUrl + requestUrl, function(response) {
        return _this.workerResponse(worker, requestUrl, response, callback);
      });
      worker.on("error", function(error) {
        var w;
        w = _this.workers.indexOf(worker);
        return _this.log(w, ("Error in " + w + ": ") + error.toString());
      });
      return this.workers.push(worker);
    };

    GelbooruCrawler.prototype.workerResponse = function(worker, url, httpResponse, callback) {
      var htmlBody, workerId,
        _this = this;
      workerId = this.workers.indexOf(worker);
      this.log(workerId, "Worker #" + workerId + " created for " + url);
      htmlBody = "";
      httpResponse.on("data", function(data) {
        return htmlBody += data;
      });
      httpResponse.on("end", function() {
        _this.log(workerId, "Worker #" + workerId + " processing data : [" + url + "]");
        callback.call(_this, worker, htmlBody);
        return _this.endWorker.call(_this, worker);
      });
      return httpResponse.on("error", function(err) {
        _this.log(workerId, ("Error in Worker #" + workerId + ": ") + err.toString() + (" : [" + url + "]"));
        return _this.endWorker.call(_this, worker);
      });
    };

    GelbooruCrawler.prototype.endWorker = function(worker) {
      var w;
      w = this.workers.indexOf(worker);
      if (w !== -1) {
        this.workers.splice(w, 1);
        return this.log(w, "Worker #" + w + " ended.");
      }
    };

    GelbooruCrawler.prototype.scanPage = function(worker, html) {
      var didMatch, image, w;
      didMatch = [];
      w = this.workers.indexOf(worker);
      while (image = this.imageIdRegExp.exec(html)) {
        didMatch.push(image[1]);
        this.resolveQueue.push(image[1]);
      }
      if (!didMatch.length) {
        this.log(w, "No images found. This was the last page. Stopping the crawler!");
        this.crawling = false;
        return this.storeDownloadList();
      } else {
        return this.log(w, "Images found: " + didMatch.join(", "));
      }
    };

    GelbooruCrawler.prototype.storeDownloadList = function() {
      return fs.writeFile("" + this.downloadPath + "/gallery.json", JSON.stringify(this.crawledImages, null, "  "), "utf-8");
    };

    GelbooruCrawler.prototype.resolveImageId = function(id) {
      var _this = this;
      return this.spawnWorker(this.viewUrl + id, function(worker, html) {
        var image, _results;
        _results = [];
        while (image = _this.imageUrlRegExp.exec(html)) {
          if (_this.crawledImages.indexOf(image[0]) === -1) {
            _this.crawledImages.push([image[0], id, _this.viewUrl + id]);
          } else {
            _this.log(null, ("Duplicate for #" + id + "/" + image[0] + " ?!").italic);
          }
          break;
        }
        return _results;
      });
    };

    GelbooruCrawler.prototype.createPath = function() {
      var date, dateLevel, dlPath, _fn, _i, _len,
        _this = this;
      date = new Date();
      this.downloadPath = __dirname;
      dateLevel = [date.getFullYear(), date.getMonth() + 1, date.getDate()];
      _fn = function(dlPath) {
        _this.downloadPath += "/" + dlPath;
        if (!fs.existsSync(_this.downloadPath)) {
          return fs.mkdir(_this.downloadPath, 755);
        }
      };
      for (_i = 0, _len = dateLevel.length; _i < _len; _i++) {
        dlPath = dateLevel[_i];
        _fn(dlPath);
      }
      this.downloadPath += "/" + this.galleryName;
      if (!fs.existsSync(this.downloadPath)) {
        fs.mkdir(this.downloadPath, 755);
      }
      return this.log(null, ("Created: " + this.downloadPath).italic);
    };

    return GelbooruCrawler;

  })();

  conf = {
    baseUrl: "http://gelbooru.com",
    maxDownloads: 6,
    maxWorkers: 5,
    renameFiles: true
  };

  test = new GelbooruCrawler("no_bra no_pants -huge* -large* -penis -*boy*", conf);

  test.search();

}).call(this);
